name: framed_coin_frontend
description: Frontend for Framed Coin

publish_to: 'none'

version: 1.0.0+11

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_bloc: ^8.1.3
  go_router: ^9.0.3
  js: ^0.6.7
  intl: ^0.18.1
  get_it: ^7.6.0
  decimal: ^2.3.3
  dropdown_button2: ^2.1.3
  flutter_spinkit: ^5.2.0
  firebase_analytics: ^10.4.4
  firebase_core: ^2.15.0
  url_launcher: ^6.1.12
  responsive_framework: ^1.1.0
  flutter_dotenv: ^5.1.0
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  equatable: ^2.0.5
  theme_provider: ^0.6.0
  toggle_switch: ^2.1.0
  font_awesome_flutter: ^10.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  bloc_test: ^9.1.3
  mocktail: ^0.3.0
  test: ^1.24.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - fonts/
    - .env

  fonts:
    - family: Righteous
      fonts:
        - asset: fonts/Righteous-Regular.ttf
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-Regular.ttf
        - asset: fonts/Comfortaa-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-Light.ttf
          weight: 300
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Bold.ttf
          weight: 700
